# Generated by Django 4.1.3 on 2022-12-17 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_usuarios'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='productos',
            new_name='producto',
        ),
        migrations.RenameModel(
            old_name='usuarios',
            new_name='usuario',
        ),
    ]
